### ISSUE TITLE
Disable all browser caching where possible

### ISSUE THREAD

**Issue by codeforger-wp** [jamesmorrison/apollo#10]
Consider commanding all browsers to no-cache such that local asset caching (css/js) does not confuse/delay developers.

see: [https://serverfault.com/questions/269420/disable-caching-when-serving-static-files-with-nginx-for-development](Link for disabling browser cache in nginx)

**Comment by jamesmorrison** [comment]
@codeforger-wp Good shout, will get this added. I'd like to sort the 2 configs (https://github.com/jamesmorrison/apollo/issues/9) first to avoid duplication of effort.

**Comment by jamesmorrison** [comment]
Resolved in https://github.com/jamesmorrison/apollo/commit/45b3779ca058aada80d3a151e617c69c75271785
